# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
test:
	@poetry run pytest --exitfirst -q tests/test_manifest_validator.py::test_manifest_validator
	@poetry run pytest --exitfirst -q tests/test_manifest_validator.py::test_oas_generator
