# SPDX-FileCopyrightText: Copyright (c) 2025 Cisco and/or its affiliates.
# SPDX-License-Identifier: Apache-2.0
# coding: utf-8

# flake8: noqa
"""
    Agent Manifest Definition

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from acp_sdk.agws_v0.models.agent_acp_specs import AgentACPSpecs
from acp_sdk.agws_v0.models.agent_acp_specs_interrupts_inner import AgentACPSpecsInterruptsInner
from acp_sdk.agws_v0.models.agent_capabilities import AgentCapabilities
from acp_sdk.agws_v0.models.agent_connect_protocol import AgentConnectProtocol
from acp_sdk.agws_v0.models.agent_deployment import AgentDeployment
from acp_sdk.agws_v0.models.agent_deployment_deployment_options_inner import AgentDeploymentDeploymentOptionsInner
from acp_sdk.agws_v0.models.agent_manifest import AgentManifest
from acp_sdk.agws_v0.models.agent_metadata import AgentMetadata
from acp_sdk.agws_v0.models.agent_reference import AgentReference
from acp_sdk.agws_v0.models.docker_deployment import DockerDeployment
from acp_sdk.agws_v0.models.lang_graph_config import LangGraphConfig
from acp_sdk.agws_v0.models.llama_index_config import LlamaIndexConfig
from acp_sdk.agws_v0.models.remote_service_deployment import RemoteServiceDeployment
from acp_sdk.agws_v0.models.source_code_deployment import SourceCodeDeployment
from acp_sdk.agws_v0.models.source_code_deployment_framework_config import SourceCodeDeploymentFrameworkConfig
from acp_sdk.agws_v0.models.streaming_modes import StreamingModes
